language: node_js

node_js:
  - '7'
  
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable

before_script:
  - "export DISPLAY=:1337"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  
install:
  - npm install
  - sleep 10
  
script:
  - ./node_modules/.bin/cypress run cypress.json --spec 'cypress/integration/examples/login1.spec.js'
